// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3Cw_4e0xAIDJrRHvXi3d6KimLrd_6hU',
    appId: '1:16305536951:web:70854791fa8c069de1f232',
    messagingSenderId: '16305536951',
    projectId: 'cft-v1-d4e82',
    authDomain: 'cft-v1-d4e82.firebaseapp.com',
    storageBucket: 'cft-v1-d4e82.firebasestorage.app',
    measurementId: 'G-VB6V8Y5B48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOcAiIdOR2DDJFDWi6zFNCKXYmI-DFDj4',
    appId: '1:16305536951:android:2948e46d60ac5353e1f232',
    messagingSenderId: '16305536951',
    projectId: 'cft-v1-d4e82',
    storageBucket: 'cft-v1-d4e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9GAXyuifWUybvc2P1gI7Yc4MLayzFF4',
    appId: '1:16305536951:ios:6f3412c49665a0eae1f232',
    messagingSenderId: '16305536951',
    projectId: 'cft-v1-d4e82',
    storageBucket: 'cft-v1-d4e82.firebasestorage.app',
    iosBundleId: 'com.example.carbonFootprintTrackerByTeamtechMads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9GAXyuifWUybvc2P1gI7Yc4MLayzFF4',
    appId: '1:16305536951:ios:6f3412c49665a0eae1f232',
    messagingSenderId: '16305536951',
    projectId: 'cft-v1-d4e82',
    storageBucket: 'cft-v1-d4e82.firebasestorage.app',
    iosBundleId: 'com.example.carbonFootprintTrackerByTeamtechMads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE3Cw_4e0xAIDJrRHvXi3d6KimLrd_6hU',
    appId: '1:16305536951:web:eb805487cf6f5964e1f232',
    messagingSenderId: '16305536951',
    projectId: 'cft-v1-d4e82',
    authDomain: 'cft-v1-d4e82.firebaseapp.com',
    storageBucket: 'cft-v1-d4e82.firebasestorage.app',
    measurementId: 'G-S0TW9TZMBV',
  );
}
